name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Dependencies
        run: |
          # Install any dependencies here
          echo "Installing dependencies..."

      - name: Deploy WordPress
        run: |
          # Deploy WordPress using your deployment script
          # For example, use SCP to transfer files to the VPS
          scp -r ./wordpress/* user@your_server_ip:/path/to/destination

      - name: Cleanup SSH Key
        run: |
          rm -f ~/.ssh/id_rsa

